version: '3.0'
networks: {rasa-network: {}}
services:
  rasa_chatbot:
    env_file:
      - ./.env
    build: .
    image: rasa-chatbot:latest
    ports:
      - 5005:5005
    volumes:
      - ./models:/app/models
      - ./config:/app/config
    command:
      - run
      - --enable-api
      - --model
      - /app/models
      - --endpoints
      - /app/config/endpoints.local.yml
    networks: [ 'rasa-network' ]
  qabot-action:
    env_file:
      - ./.env
    image: sapan1812/qabotactions:1.1
    ports:
      - 5055:5055
    networks: [ 'rasa-network' ]
  duckling:
    image: rasa/duckling:latest
    ports:
      - "8000:8000"
    networks: [ 'rasa-network' ]